import Image from "next/image";

// Public, unauthenticated page (see src/proxy.ts) — exists mainly to satisfy
// Intuit's requirement for a public EULA URL before issuing QuickBooks
// Online Production API keys. This app is an internal tool for Lockdown IT
// staff, with a couple of public-token pages for customers (quote review,
// MSA signing, the new-customer intake form) — this EULA covers use of the
// staff-facing application itself.
export default function EulaPage() {
  return (
    <div className="min-h-screen bg-slate-100 py-10 print:bg-white print:py-0">
      <div className="mx-auto max-w-3xl rounded-xl bg-white shadow-lg print:shadow-none">
        <div className="flex items-center justify-center rounded-t-xl border-b border-slate-100 bg-white px-8 py-5">
          <Image src="/lockdown-logo.png" alt="Lockdown IT" width={5052} height={1264} className="h-10 w-auto" priority />
        </div>

        <div className="px-8 py-8">
          <p className="text-xs font-semibold uppercase tracking-widest text-[#1d98eb]">Lockdown IT</p>
          <h1 className="mt-1 text-2xl font-semibold text-[#024996]">End-User License Agreement</h1>
          <p className="mt-1 text-sm text-slate-500">Last updated {new Date().toLocaleDateString()}</p>

          <div className="mt-6 flex flex-col gap-5 text-sm leading-relaxed text-slate-700">
            <p>
              This application (the &ldquo;Software&rdquo;) is an internal quoting, customer-relationship, and billing
              tool built for and operated by Lockdown IT (&ldquo;Lockdown IT,&rdquo; &ldquo;we,&rdquo; or
              &ldquo;us&rdquo;). It is not distributed or licensed to the general public. This End-User License
              Agreement (&ldquo;Agreement&rdquo;) governs use of the Software by Lockdown IT&rsquo;s authorized staff
              and by customers interacting with the specific customer-facing pages the Software generates (quote
              review pages, Master Service Agreement review/e-signing pages, and the new-customer intake form).
            </p>

            <div>
              <h2 className="mb-1.5 text-sm font-semibold text-[#024996]">1. License grant</h2>
              <p>
                Lockdown IT grants its authorized staff a limited, non-transferable, revocable right to access and
                use the Software solely for Lockdown IT&rsquo;s internal business purposes. No license, ownership
                interest, or other right in the Software is granted to any other party by virtue of viewing,
                reviewing, or signing a document generated by the Software.
              </p>
            </div>

            <div>
              <h2 className="mb-1.5 text-sm font-semibold text-[#024996]">2. Ownership</h2>
              <p>
                The Software, including its source code, design, and underlying technology, is and remains the
                property of Lockdown IT. Nothing in this Agreement transfers any intellectual property rights.
              </p>
            </div>

            <div>
              <h2 className="mb-1.5 text-sm font-semibold text-[#024996]">3. Acceptable use</h2>
              <p>
                Users may not attempt to gain unauthorized access to the Software or the data it processes, use it
                to violate any applicable law, or use it to transmit unlawful, abusive, or harmful content.
              </p>
            </div>

            <div>
              <h2 className="mb-1.5 text-sm font-semibold text-[#024996]">4. Third-party services</h2>
              <p>
                The Software integrates with third-party services — including QuickBooks Online for invoicing and a
                transactional email provider for notifications — solely to support Lockdown IT&rsquo;s internal
                operations. Use of those third-party services remains subject to that provider&rsquo;s own terms.
              </p>
            </div>

            <div>
              <h2 className="mb-1.5 text-sm font-semibold text-[#024996]">5. No warranty; limitation of liability</h2>
              <p>
                The Software is provided &ldquo;as is&rdquo; without warranties of any kind. To the fullest extent
                permitted by law, Lockdown IT disclaims all warranties and will not be liable for any indirect,
                incidental, or consequential damages arising from use of the Software.
              </p>
            </div>

            <div>
              <h2 className="mb-1.5 text-sm font-semibold text-[#024996]">6. Changes</h2>
              <p>
                Lockdown IT may update this Agreement from time to time by posting a revised version at this URL.
              </p>
            </div>

            <div>
              <h2 className="mb-1.5 text-sm font-semibold text-[#024996]">7. Contact</h2>
              <p>
                Questions about this Agreement can be directed to Lockdown IT through the contact information
                provided on your quote, agreement, or invoice.
              </p>
            </div>

            <p className="rounded-md border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">
              This is a general-purpose template and not a substitute for advice from an attorney licensed in your
              jurisdiction — consider having it reviewed before relying on it further.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
